
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shell_command:
  update_and_restart_ha: "/bin/bash /home/melanie/homeassistant/config/scripts/update_and_restart.sh"

template:
  - sensor: !include area_device_count_sensors.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/better-thermostat-ui-card/better-thermostat-ui-card.js
      type: module
    - url: /hacsfiles/Bubble-Card/bubble-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/homeassistant-minimalistic-area-card/minimalistic-area-card.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/slider-button-card/button-card.js
      type: module
    - url: /hacsfiles/weather-radar-card/weather-radar-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
  dashboards:
    mobile-dashboard:
      mode: yaml
      title: Mobile Dashboard
      icon: mdi:cellphone
      show_in_sidebar: false
      filename: dashboards/mobile_dashboard.yaml
    tablet-dashboard:
      mode: yaml
      title: Overview
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      filename: dashboards/tablet_dashboard.yaml